### ISSUE TITLE
Did you forget to commit the test dir?

### ISSUE THREAD

**Issue by kasbah** [EFanZh/Graphviz-Preview#6]
Hello! When I run `npm test` I get:

```

> graphviz-preview@0.0.3 test /tmp/Graphviz-Preview
> node ./node_modules/vscode/bin/test

### VS Code Extension Test Run ###
Current working directory: /tmp/Graphviz-Preview
Running extension tests: /tmp/Graphviz-Preview/.vscode-test/VSCode-linux-x64/code /tmp/Graphviz-Preview/test --extensionDevelopmentPath=/tmp/Graphviz-Preview --extensionTestsPath=/tmp/Graphviz-Preview/test
bash: cannot set terminal process group (-1): Inappropriate ioctl for device
bash: no job control in this shell

Error: Error: Cannot find module '/tmp/Graphviz-Preview/test'
	at t.handleExtensionTests (/tmp/Graphviz-Preview/.vscode-test/VSCode-linux-x64/resources/app/out/vs/workbench/node/extensionHostProcess.js:533:22)
	at /tmp/Graphviz-Preview/.vscode-test/VSCode-linux-x64/resources/app/out/vs/workbench/node/extensionHostProcess.js:529:515
	at Object.g [as _notify] (/tmp/Graphviz-Preview/.vscode-test/VSCode-linux-x64/resources/app/out/vs/workbench/node/extensionHostProcess.js:67:449)
	at Object.enter (/tmp/Graphviz-Preview/.vscode-test/VSCode-linux-x64/resources/app/out/vs/workbench/node/extensionHostProcess.js:70:778)
	at n.Class.derive._creator._run (/tmp/Graphviz-Preview/.vscode-test/VSCode-linux-x64/resources/app/out/vs/workbench/node/extensionHostProcess.js:72:573)
	at n.Class.derive._creator._completed (/tmp/Graphviz-Preview/.vscode-test/VSCode-linux-x64/resources/app/out/vs/workbench/node/extensionHostProcess.js:72:14)
	at n.Class.define.cancel.then (/tmp/Graphviz-Preview/.vscode-test/VSCode-linux-x64/resources/app/out/vs/workbench/node/extensionHostProcess.js:73:984)
	at Object.enter (/tmp/Graphviz-Preview/.vscode-test/VSCode-linux-x64/resources/app/out/vs/workbench/node/extensionHostProcess.js:69:863)
	at n.Class.derive._creator._run (/tmp/Graphviz-Preview/.vscode-test/VSCode-linux-x64/resources/app/out/vs/workbench/node/extensionHostProcess.js:72:573)
	at n.Class.derive._creator._setCompleteValue (/tmp/Graphviz-Preview/.vscode-test/VSCode-linux-x64/resources/app/out/vs/workbench/node/extensionHostProcess.js:72:267)
	at Object.g [as _notify] (/tmp/Graphviz-Preview/.vscode-test/VSCode-linux-x64/resources/app/out/vs/workbench/node/extensionHostProcess.js:67:429)
	at Object.enter (/tmp/Graphviz-Preview/.vscode-test/VSCode-linux-x64/resources/app/out/vs/workbench/node/extensionHostProcess.js:70:778)
	at n.Class.derive._oncancel._run (/tmp/Graphviz-Preview/.vscode-test/VSCode-linux-x64/resources/app/out/vs/workbench/node/extensionHostProcess.js:72:573)
	at n.Class.derive._oncancel._completed (/tmp/Graphviz-Preview/.vscode-test/VSCode-linux-x64/resources/app/out/vs/workbench/node/extensionHostProcess.js:72:14)
	at e.open (/tmp/Graphviz-Preview/.vscode-test/VSCode-linux-x64/resources/app/out/vs/workbench/node/extensionHostProcess.js:96:723)
	at /tmp/Graphviz-Preview/.vscode-test/VSCode-linux-x64/resources/app/out/vs/workbench/node/extensionHostProcess.js:508:268

Tests exited with code: 1
npm ERR! Test failed.  See above for more details.
```

I was wondering if there is maybe supposed to be a test directory that's not in the Git repo?

**Comment by EFanZh** [comment]
@kasbah No, I didn’t write tests for this project. I’ll add this to my TODO list.

**Comment by EFanZh** [comment]
The tests have been added to the master branch.
